[build]
    command = "npm run build"
    publish = "dist"

[[headers]]
    for  = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; frame-ancestors 'self'; upgrade-insecure-requests; object-src 'none'; base-uri 'self';"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Cross-Origin-Resource-Policy = "same-origin"